// <auto-generated />
using System;
using FamilyTreeApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyTreeApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804030943_NormalizeRosterTableNames")]
    partial class NormalizeRosterTableNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyTreeApp.Domain.Roster.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("FamilyMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VisibilityStatus")
                        .HasColumnType("integer")
                        .HasColumnName("visibility_status");

                    b.HasKey("FamilyMemberId");

                    b.ToTable("roster_family_members", (string)null);
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Roster.Entities.FamilyMemberRelationship", b =>
                {
                    b.Property<Guid>("FamilyMemberRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_relationship_id");

                    b.Property<Guid>("BaseFamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_family_member_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RelatedFamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_family_member_id");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FamilyMemberRelationshipId");

                    b.HasIndex("TreeId", "BaseFamilyMemberId");

                    b.HasIndex("BaseFamilyMemberId", "RelatedFamilyMemberId", "RelationshipType")
                        .IsUnique();

                    b.ToTable("roster_family_member_relationships", (string)null);
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Trees.Entities.Tree", b =>
                {
                    b.Property<Guid>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TreeId");

                    b.HasIndex("Name");

                    b.ToTable("trees_tree", (string)null);
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Trees.Entities.TreeRbac", b =>
                {
                    b.Property<Guid>("TreeRbacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tree_rbac_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TreeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tree_id");

                    b.Property<int>("TreeRole")
                        .HasColumnType("integer")
                        .HasColumnName("tree_role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TreeRbacId");

                    b.HasIndex("UserId");

                    b.HasIndex("TreeId", "UserId")
                        .IsUnique();

                    b.ToTable("trees_tree_rbac", (string)null);
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Users.Entities.ExternalLogin", b =>
                {
                    b.Property<Guid>("ExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("external_login_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ExternalLoginId");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("users_external_logins", (string)null);
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users_user", (string)null);
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Roster.Entities.FamilyMember", b =>
                {
                    b.OwnsOne("FamilyTreeApp.Domain.ValueObjects.ProfileInfo", "ProfileInfo", b1 =>
                        {
                            b1.Property<Guid>("FamilyMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("avatar_url");

                            b1.Property<string>("Bio")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("bio");

                            b1.Property<DateTime?>("BirthDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_of_birth");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<int?>("Gender")
                                .HasMaxLength(50)
                                .HasColumnType("integer")
                                .HasColumnName("gender");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("phone_number");

                            b1.HasKey("FamilyMemberId");

                            b1.ToTable("roster_family_members");

                            b1.WithOwner()
                                .HasForeignKey("FamilyMemberId");
                        });

                    b.Navigation("ProfileInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Roster.Entities.FamilyMemberRelationship", b =>
                {
                    b.HasOne("FamilyTreeApp.Domain.Roster.Entities.FamilyMember", null)
                        .WithMany("Relationships")
                        .HasForeignKey("BaseFamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Trees.Entities.TreeRbac", b =>
                {
                    b.HasOne("FamilyTreeApp.Domain.Trees.Entities.Tree", "Tree")
                        .WithMany("TreeRbacs")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTreeApp.Domain.Users.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Users.Entities.ExternalLogin", b =>
                {
                    b.HasOne("FamilyTreeApp.Domain.Users.Entities.User", null)
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Users.Entities.User", b =>
                {
                    b.OwnsOne("FamilyTreeApp.Domain.ValueObjects.ProfileInfo", "ProfileInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("avatar_url");

                            b1.Property<string>("Bio")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("bio");

                            b1.Property<DateTime?>("BirthDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_of_birth");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<int?>("Gender")
                                .HasMaxLength(50)
                                .HasColumnType("integer")
                                .HasColumnName("gender");

                            b1.Property<string>("LastName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("phone_number");

                            b1.HasKey("UserId");

                            b1.ToTable("users_user");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("ProfileInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Roster.Entities.FamilyMember", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Trees.Entities.Tree", b =>
                {
                    b.Navigation("TreeRbacs");
                });

            modelBuilder.Entity("FamilyTreeApp.Domain.Users.Entities.User", b =>
                {
                    b.Navigation("ExternalLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
